<?php
require __DIR__.'/config/config.php';
$pdo=db();
$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);
$base=rtrim(dirname($_SERVER['SCRIPT_NAME']),'/');$route=preg_replace('#^'.preg_quote($base,'#').'#','',$path);$route=trim($route,'/');
function page_header($title){?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($title)?> · Security Compliance</title><link rel="stylesheet" href="assets/app.css"><script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script></head><body><aside><div class="brand"><span>SC</span><div><b>Security</b><small>Compliance Platform</small></div></div><nav><a href="?p=dashboard">◈ Dashboard</a><a href="?p=assets">▣ Assets</a><a href="?p=assessment">✓ Assessment</a><a href="?p=findings">⚠ Findings</a><a href="?p=controls">⚙ Controls</a></nav><div class="side-note">YES = compliant<br>NO = gap<br>N/A = excluded</div></aside><main><header><div><div class="eyebrow">SECURITY POSTURE</div><h1><?=htmlspecialchars($title)?></h1></div><div class="top-status"><i></i> Assessment workspace</div></header><?php}
function page_footer(){?></main><script src="assets/app.js"></script></body></html><?php}
$p=$_GET['p']??'dashboard';
if($p==='dashboard'){
 $rows=$pdo->query("SELECT a.type, COUNT(CASE WHEN x.status='YES' THEN 1 END) yes,COUNT(CASE WHEN x.status='NO' THEN 1 END) no,COUNT(CASE WHEN x.status IN('YES','NO') THEN 1 END) total FROM assessments x JOIN assets a ON a.id=x.asset_id GROUP BY a.type")->fetchAll();
 $yes=(int)$pdo->query("SELECT COUNT(*) FROM assessments WHERE status='YES'")->fetchColumn();$no=(int)$pdo->query("SELECT COUNT(*) FROM assessments WHERE status='NO'")->fetchColumn();$na=(int)$pdo->query("SELECT COUNT(*) FROM assessments WHERE status='N/A'")->fetchColumn();$score=$yes+$no?round($yes/($yes+$no)*100):0;$assetCount=(int)$pdo->query('SELECT COUNT(*) FROM assets WHERE active=1')->fetchColumn();
 page_header('Security Dashboard');?><section class="hero"><div><span class="pill">LIVE CHECKLIST</span><h2>Know what is actually protected.</h2><p>Simple YES / NO / N/A security compliance assessment across Network, Server and Endpoint.</p></div><div class="score-ring" style="--score:<?=$score*3.6?>deg"><strong><?=$score?>%</strong><small>overall</small></div></section><div class="stats"><div><small>Assets</small><b><?=$assetCount?></b><em>in scope</em></div><div><small>Compliant</small><b><?=$yes?></b><em>YES controls</em></div><div><small>Open gaps</small><b><?=$no?></b><em>NO controls</em></div><div><small>Excluded</small><b><?=$na?></b><em>N/A controls</em></div></div><div class="grid2"><section class="card"><div class="card-head"><div><small>DOMAIN COMPLIANCE</small><h3>Posture by domain</h3></div></div><canvas id="domainChart" height="220"></canvas></section><section class="card"><div class="card-head"><div><small>ASSESSMENT MIX</small><h3>Control results</h3></div></div><canvas id="mixChart" height="220"></canvas></section></div><section class="card"><div class="card-head"><div><small>DOMAIN SNAPSHOT</small><h3>Where to focus</h3></div><a class="btn" href="?p=assessment">Open assessment</a></div><div class="domain-list"><?php foreach($rows as $r){$s=$r['total']?round($r['yes']/$r['total']*100):0;?><div class="domain-row"><b><?=$r['type']?></b><div class="bar"><i style="width:<?=$s?>%"></i></div><strong><?=$s?>%</strong><span><?=$r['no']?> gaps</span></div><?php }?></div></section><script>window.domainData=<?=json_encode($rows)?>;window.mixData=[<?=$yes?>,<?=$no?>,<?=$na?>];</script><?php page_footer();
}elseif($p==='assets'){
 $type=$_GET['type']??'';$stmt=$type?$pdo->prepare('SELECT * FROM assets WHERE type=? AND active=1 ORDER BY type,name'): $pdo->prepare('SELECT * FROM assets WHERE active=1 ORDER BY type,name');$type?$stmt->execute([$type]):$stmt->execute();$assets=$stmt->fetchAll();page_header('Assets');?><section class="toolbar"><div><span class="pill">INVENTORY</span><h2>Security assets</h2><p>Add any device here — Network, Server, Endpoint or a future asset type.</p></div><a class="btn primary" href="?p=asset_new">+ Add asset</a></section><div class="filters"><a class="chip" href="?p=assets">All</a><a class="chip" href="?p=assets&type=Network">Network</a><a class="chip" href="?p=assets&type=Server">Server</a><a class="chip" href="?p=assets&type=Endpoint">Endpoint</a></div><section class="card table-wrap"><table><thead><tr><th>Asset</th><th>Type</th><th>Location</th><th>IP</th><th>Owner</th><th></th></tr></thead><tbody><?php foreach($assets as $a):?><tr><td><b><?=$a['name']?></b><small><?=$a['asset_code']?></small></td><td><span class="tag <?=$a['type']?>"><?=$a['type']?></span></td><td><?=$a['location']?></td><td class="mono"><?=$a['ip_address']?></td><td><?=$a['owner']?></td><td><a href="?p=assessment&asset=<?=$a['id']?>" class="link">Assess →</a></td></tr><?php endforeach;?></tbody></table></section><?php page_footer();
}elseif($p==='asset_new'){
 if($_SERVER['REQUEST_METHOD']==='POST'){$s=$pdo->prepare('INSERT INTO assets(asset_code,name,type,location,ip_address,owner) VALUES(?,?,?,?,?,?)');$s->execute([$_POST['asset_code'],$_POST['name'],$_POST['type'],$_POST['location'],$_POST['ip_address'],$_POST['owner']]);header('Location:?p=assets');exit;}page_header('Add Asset');?><section class="card form-card"><form method="post"><div class="form-grid"><label>Asset code<input name="asset_code" required placeholder="NET-003"></label><label>Asset name<input name="name" required placeholder="Firewall Branch A"></label><label>Type<select name="type"><option>Network</option><option>Server</option><option>Endpoint</option></select></label><label>Location<input name="location" placeholder="DC JTP"></label><label>IP address<input name="ip_address" placeholder="10.10.10.1"></label><label>Owner<input name="owner" placeholder="IT Infrastructure"></label></div><div class="form-actions"><a class="btn" href="?p=assets">Cancel</a><button class="btn primary">Save asset</button></div></form></section><?php page_footer();
}elseif($p==='assessment'){
 $assetId=(int)($_GET['asset']??0);$assets=$pdo->query('SELECT * FROM assets WHERE active=1 ORDER BY type,name')->fetchAll();if(!$assetId&&$assets)$assetId=$assets[0]['id'];$asset=null;foreach($assets as $a)if($a['id']==$assetId)$asset=$a;if(!$asset){page_header('Assessment');echo '<section class="card empty">No asset found.</section>';page_footer();exit;}$cs=$pdo->prepare('SELECT c.*,d.name domain,(SELECT status FROM assessments x WHERE x.asset_id=? AND x.control_id=c.id) status,(SELECT notes FROM assessments x WHERE x.asset_id=? AND x.control_id=c.id) notes FROM controls c JOIN domains d ON d.id=c.domain_id WHERE d.name=? AND c.active=1 ORDER BY c.id');$cs->execute([$assetId,$assetId,$asset['type']]);$controls=$cs->fetchAll();if($_SERVER['REQUEST_METHOD']==='POST'){foreach($controls as $c){$status=$_POST['status'][$c['id']]??'N/A';$note=$_POST['notes'][$c['id']]??'';$q=$pdo->prepare('INSERT INTO assessments(asset_id,control_id,status,notes) VALUES(?,?,?,?) ON CONFLICT(asset_id,control_id) DO UPDATE SET status=excluded.status,notes=excluded.notes,assessed_at=CURRENT_TIMESTAMP');$q->execute([$assetId,$c['id'],$status,$note]);}header('Location:?p=assessment&asset='.$assetId.'&saved=1');exit;}$yes=$no=$na=0;foreach($controls as $c){${strtolower($c['status']??'na')}++;}$den=$yes+$no;$score=$den?round($yes/$den*100):0;page_header('Assessment');?><section class="toolbar"><div><span class="pill"><?=$asset['type']?></span><h2><?=$asset['name']?></h2><p class="mono"><?=$asset['asset_code']?> · <?=$asset['ip_address']?> · <?=$asset['location']?></p></div><div class="mini-score"><b><?=$score?>%</b><small><?=$yes?> YES / <?=$no?> NO / <?=$na?> N/A</small></div></section><form method="post"><section class="card checklist"><div class="card-head"><div><small>SECURITY CONTROLS</small><h3>Checklist</h3></div></div><?php foreach($controls as $c):?><div class="check-row"><div><b><?=$c['name']?></b><small><?=$c['description']?></small></div><select name="status[<?=$c['id']?>]" class="status-<?=$c['status']??'N/A'?>"><option <?=$c['status']==='YES'?'selected':''?>>YES</option><option <?=$c['status']==='NO'?'selected':''?>>NO</option><option <?=$c['status']==='N/A'?'selected':''?>>N/A</option></select><input name="notes[<?=$c['id']?>]" value="<?=htmlspecialchars($c['notes']??'')?>" placeholder="Optional note / evidence"></div><?php endforeach;?></section><div class="form-actions"><button class="btn primary">Save assessment</button></div></form><?php page_footer();
}elseif($p==='findings'){
 $f=$pdo->query('SELECT f.*,a.name asset,c.name control FROM findings f JOIN assets a ON a.id=f.asset_id JOIN controls c ON c.id=f.control_id ORDER BY f.id DESC')->fetchAll();page_header('Findings');?><section class="toolbar"><div><span class="pill">NON-COMPLIANCE</span><h2>Security findings</h2><p>Every NO can become an actionable remediation item.</p></div></section><section class="card table-wrap"><table><thead><tr><th>Finding</th><th>Asset</th><th>Control</th><th>Severity</th><th>Status</th></tr></thead><tbody><?php if(!$f):?><tr><td colspan="5" class="empty">No findings yet. Use NO controls as the trigger for future finding automation.</td></tr><?php endif;foreach($f as $x):?><tr><td><b><?=$x['title']?></b><small><?=$x['description']?></small></td><td><?=$x['asset']?></td><td><?=$x['control']?></td><td><span class="severity <?=$x['severity']?>"><?=$x['severity']?></span></td><td><?=$x['status']?></td></tr><?php endforeach;?></tbody></table></section><?php page_footer();
}elseif($p==='controls'){
 $rows=$pdo->query('SELECT c.*,d.name domain FROM controls c JOIN domains d ON d.id=c.domain_id ORDER BY d.id,c.id')->fetchAll();page_header('Security Controls');?><section class="toolbar"><div><span class="pill">CONFIGURABLE</span><h2>Security controls</h2><p>This is the key to flexible assessment: add a control once, then it appears automatically for matching assets.</p></div></section><section class="card table-wrap"><table><thead><tr><th>Domain</th><th>Control</th><th>Weight</th><th>Active</th></tr></thead><tbody><?php foreach($rows as $x):?><tr><td><span class="tag <?=$x['domain']?>"><?=$x['domain']?></span></td><td><b><?=$x['name']?></b></td><td><?=$x['weight']?></td><td><?=$x['active']?'YES':'NO'?></td></tr><?php endforeach;?></tbody></table></section><?php page_footer();
}else{header('Location:?p=dashboard');exit;}
